services:
  mongodb:
    image: docker.io/library/mongo:6
    ports: ["27017:27017"]

  fastapi:
    build: .
    ports: ["8000:8000"]
    depends_on: [mongodb]
    volumes: [".:/app"]
    environment:
      - ENV=local
      - DEBUG=True

  mongo-express:
    image: docker.io/library/mongo-express:1.0.2-20
    ports: ["8081:8081"]
    depends_on: [mongodb]
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
